In [1]:
#Question 1
import numpy as np

a = np.array([[1, 2, 3],[4, 5, 6]])

a = a.tolist()

print(a)

[[1, 2, 3], [4, 5, 6]]


In [2]:
#Question 2
import numpy as np

a = np.array([[7, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
b = np.trace(a)

print(b)

21


In [3]:
#Question 3
import numpy as np

a = np.array([[1, 2, 3],
            [4, 5, 6]])
print("Values bigger than X =", a[a>3])

Values bigger than X = [4 5 6]


In [4]:
#Question 4
import numpy as np

a = np.array([[1, 2, 3],
            [4, 5, 6]])

b = np.array([[2, 4, 6],
            [8, 10, 12]])

c = np.add(a,b)

print(c)

[[ 3  6  9]
 [12 15 18]]


In [6]:
#Question 5
import numpy as np

a = np.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])

mean = a - a.mean(axis=1 , keepdims=True)
print(mean)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]
